apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-rds-metrics
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: fetch-metrics
    functionRef:
      name: function-rds-metrics
    input:
      apiVersion: rdsmetrics.fn.crossplane.io/v1beta1
      kind: Input
      databaseName: "database-1"
      region: "us-east-1"
      metrics:
      - "CPUCreditUsage"
      - "CPUUtilization"
      - "DatabaseConnections"
      - "DBLoad"
      period: 10800
      target: "status.metricResults"
    credentials:
      - name: aws-creds
        source: Secret
        secretRef:
          namespace: crossplane-system
          name: aws-creds
